from . import contract_line
from . import course_line
from . import course_table
from . import hr_employee
from . import product_template
from . import res_partner
from . import student_contract
from . import student_subject_line
from . import term_subject
